<a href="https://colab.research.google.com/github/pavanibasanth/pavani_INFO5731_Fall2024/blob/main/Kommineni_pavani_Exercise_03_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [1]:
# Your answer here (no code for this question; write down your answer as detail as possible for the above questions):
Text = '''

             Classification: An analysis of Sentiments found in product reviews
   The most enjoyable text classification task that will be implemented in this assignment is the sentiment analysis of the product reviews.
This task is expected to sort customers' feedback; for instance, we may categorize it as positive, neutral, or negative.
Businesses can use such analysis to extend the knowledge acquired from their clients to improve their services and goods based on the encouraging comments obtained (Shivaprasad & Shetty, 2017).
For this, feature extraction from the self-text data enables the generation of a machine-learning algorithm capable of distinguishing the type of sentiment in the provided reviews. Here are five types of features that are useful for this task:

1. Bags of Words (BoW)
  The model shows an example of a text representation method in which the text gets quantized, with each document viewed as an unordered bag of words.
In this model, each document can be quantitatively described by a frequency vector, word count frequencies, or direct frequency of occurrence of the word in the document, irrespective of the word location and context it pertains to (AlQahtani, 2021).
The Bag of Words methodology assists companies in converting textual information for machine learning competency for easier analysis.
The text transformation of Bags of Words into numerical format allows models to identify the presence and occurrence of significant terms such as fantastic, amazing, terrible, and so on (AlQahtani, 2021).

2. Sentiment Lexicon Features
  This model refers to a collection of words that are predefined and are either positive or negative (e.g., good and excellent vs. "bad" and "terrible")(AlQahtani, 2021).
Assigning word weights concerning the positioned positive or negative sentiment is also possible. Adding this feature benefits sorting through the content to produce a suitable, accurate sentiment(Dey et al. 2018).

3. Part of Speech (POS) Tags
  POS tagging consists of assigning descriptive tags to every word form in a sentence, including nouns, verbs, adjectives, and adverbs. Many adjectives and adverbs contain sentiment.
For example, words such as amazing, fantastic, or awful are normally adjectives that express the intensity of the feeling.
When POS tags are included as features, the repetitive words in the expressions are prevented, and the model can give them importance (Senthil & Malarvizhi, 2020).

4. Term Frequency-Inverse Document Frequency (TF-IDF)
  It reflects the importance of a word in the document according to a corpus.
Its ranks are determined by the frequency with which a word appears in the document and how rare it is in the collection.
It assists in identifying unique words that may be used in expressing the sentiment (Rahman et al., 2020).
For example, words that often appear in negative reviews but rarely in different settings are given more significance.

5. N-grams (Bigrams, Trigrams)
	N-grams are n-word sequences used to analyze texts and documents.
They were created employing bigram (two related terms) and trigram (three linked terms).
The capture of word order and context is critical when considering positive and negative words (Dey et al., 2018).
Examples of such trigger words include highly recommend and poor quality since words like recommend or poor indicate a certain level of sentiment.


References
AlQahtani, A. S. (2021). Product sentiment analysis for Amazon reviews. International Journal of Computer Science & Information Technology (IJCSIT) Vol, 13.
Dey, A., Jenamani, M., & Thakkar, J. J. (2018). Senti-N-Gram: An n-gram lexicon for sentiment analysis. Expert Systems with Applications, 103, 92-105.
Rahman, S. S. M. M., Biplob, K. B. M. B., Rahman, M. H., Sarker, K., & Islam, T. (2020). An investigation and evaluation of N-Gram, TF-IDF and ensemble methods in sentiment classification. In Cyber Security and Computer Science: Second EAI International Conference, ICONCS 2020, Dhaka, Bangladesh, February 15-16, 2020, Proceedings 2 (pp. 391-402). Springer International Publishing.
Senthil Kumar, B., & Malarvizhi, N. (2020). Bi-directional LSTM_CNN combined method for sentiment analysis in part of speech tagging (PoS). International Journal of Speech Technology, 23, 373-380.
Shivaprasad, T. K., & Shetty, J. (2017, March). Sentiment analysis of product reviews: A review. In 2017 International conference on inventive communication and computational technologies (ICICCT) (pp. 298-301). IEEE.













'''


print(Text)













             Classification: An analysis of Sentiments found in product reviews
   The most enjoyable text classification task that will be implemented in this assignment is the sentiment analysis of the product reviews.
This task is expected to sort customers' feedback; for instance, we may categorize it as positive, neutral, or negative.
Businesses can use such analysis to extend the knowledge acquired from their clients to improve their services and goods based on the encouraging comments obtained (Shivaprasad & Shetty, 2017).
For this, feature extraction from the self-text data enables the generation of a machine-learning algorithm capable of distinguishing the type of sentiment in the provided reviews. Here are five types of features that are useful for this task:

1. Bags of Words (BoW)
  The model shows an example of a text representation method in which the text gets quantized, with each document viewed as an unordered bag of words.
In this model, each document can be quantit

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [2]:
# You code here (Please add comments in the code):
# Import Required libraries
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.sentiment import SentimentIntensityAnalyzer
import pandas as pd


#  Sample data of the product reviews
reviews = [
    "I absolutely love this product! It works amazingly well.",
    "The product is okay, but not what I had hoped for.",
    "Not happy with the quality, I expected something better.",
    "This is a terrible product, I will never buy it again.",
    "Fantastic quality! Highly recommend to everyone."
]

# 1. Bag of Words (BoW) feature extraction
vectorizer = CountVectorizer()
# Reviews fitting and transformation
R_bow = vectorizer.fit_transform(reviews)
print("1. Bag of Words Features:\n", R_bow.toarray())

# 2. Sentiment Lexicon (Using VADER in performing the analysis)
nltk.download('vader_lexicon')
senta = SentimentIntensityAnalyzer()
sentiment_scores = [senta.polarity_scores(review) for review in reviews]
print("\n2. Sentiment Lexicon Features (VADER scores):")
for review, score in zip(reviews, sentiment_scores):
    print(f"Review: {review}\nSentiment Scores: {score}\n")

# 3. Part of Speech (POS) Tags
#Downloading Tokenizer- a model used for splitting text into words/sentences
nltk.download('punkt')
#Downloading model for tagging parts of the speech
nltk.download('averaged_perceptron_tagger')
print(" 3. POS Tags for Each text given in the Review")
for review in reviews:
    tokens = word_tokenize(review)
    pos_tags = pos_tag(tokens)
    print(f"Review: {review}\nPOS Tags: {pos_tags} \n")
# 4. TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(2, 3))
tfidf_matrix = tfidf_vectorizer.fit_transform(reviews)
print("\n 4. TF-IDF Matrix using (Bigrams & Trigrams):\n",)
print(tfidf_vectorizer.get_feature_names_out())
print(tfidf_matrix.toarray())

# 5. N-grams (Bigrams & Trigrams)
# CountVectorizer to generate bigrams and trigrams (n-gram range from 2 to 3)
vectorizer = CountVectorizer(ngram_range=(2, 3), stop_words='english')
ngrams = vectorizer.fit_transform(reviews)
print("Bigrams and Trigrams (2-grams & 3-grams):")
print(vectorizer.get_feature_names_out())
print(ngrams.toarray())


1. Bag of Words Features:
 [[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0]]


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...



2. Sentiment Lexicon Features (VADER scores):
Review: I absolutely love this product! It works amazingly well.
Sentiment Scores: {'neg': 0.0, 'neu': 0.455, 'pos': 0.545, 'compound': 0.8008}

Review: The product is okay, but not what I had hoped for.
Sentiment Scores: {'neg': 0.227, 'neu': 0.654, 'pos': 0.119, 'compound': -0.3239}

Review: Not happy with the quality, I expected something better.
Sentiment Scores: {'neg': 0.252, 'neu': 0.504, 'pos': 0.244, 'compound': -0.0253}

Review: This is a terrible product, I will never buy it again.
Sentiment Scores: {'neg': 0.279, 'neu': 0.721, 'pos': 0.0, 'compound': -0.4767}

Review: Fantastic quality! Highly recommend to everyone.
Sentiment Scores: {'neg': 0.0, 'neu': 0.374, 'pos': 0.626, 'compound': 0.7707}



[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


 3. POS Tags for Each text given in the Review
Review: I absolutely love this product! It works amazingly well.
POS Tags: [('I', 'PRP'), ('absolutely', 'RB'), ('love', 'VBP'), ('this', 'DT'), ('product', 'NN'), ('!', '.'), ('It', 'PRP'), ('works', 'VBZ'), ('amazingly', 'RB'), ('well', 'RB'), ('.', '.')] 

Review: The product is okay, but not what I had hoped for.
POS Tags: [('The', 'DT'), ('product', 'NN'), ('is', 'VBZ'), ('okay', 'JJ'), (',', ','), ('but', 'CC'), ('not', 'RB'), ('what', 'WP'), ('I', 'PRP'), ('had', 'VBD'), ('hoped', 'VBN'), ('for', 'IN'), ('.', '.')] 

Review: Not happy with the quality, I expected something better.
POS Tags: [('Not', 'RB'), ('happy', 'JJ'), ('with', 'IN'), ('the', 'DT'), ('quality', 'NN'), (',', ','), ('I', 'PRP'), ('expected', 'VBD'), ('something', 'NN'), ('better', 'RBR'), ('.', '.')] 

Review: This is a terrible product, I will never buy it again.
POS Tags: [('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('terrible', 'JJ'), ('product', 'NN'), (',', '

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
# You code here (Please add comments in the code):

# Import necessary libraries
from sklearn.feature_selection import chi2
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# Labels for the reviews (1 for positive, 0 for negative)
labels = [1, 0, 0, 0, 1]  # Positive = 1, Negative = 0

# 1. Bigrams and Trigrams Feature Extraction
vectorizer = CountVectorizer(ngram_range=(2, 3), stop_words='english')
X = vectorizer.fit_transform(reviews)
feature_names = vectorizer.get_feature_names_out()

# 2. Apply Chi-Square for Feature Selection
chi2_scores, p_values = chi2(X, labels)

# 3. Ranking the features by Chi-Square score
# Sorting features by the highest chi2 score (descending order)
sorted_idx = np.argsort(chi2_scores)[::-1]
sorted_feature_names = feature_names[sorted_idx]
sorted_chi2_scores = chi2_scores[sorted_idx]

# Showing top features according to its essense
print("Top Features Ranked by Importance (Chi-Square Score):")
print(" \n Top Features.............Scores\n")
for feature, score in zip(sorted_feature_names, sorted_chi2_scores):

     print(f"{feature}: {score:.2f}")





Top Features Ranked by Importance (Chi-Square Score):
 
 Top Features.............Scores

works amazingly: 1.50
product works: 1.50
absolutely love product: 1.50
fantastic quality: 1.50
fantastic quality highly: 1.50
highly recommend: 1.50
love product: 1.50
love product works: 1.50
absolutely love: 1.50
product works amazingly: 1.50
quality highly: 1.50
quality highly recommend: 1.50
product okay hoped: 0.67
product okay: 0.67
terrible product buy: 0.67
okay hoped: 0.67
quality expected: 0.67
quality expected better: 0.67
happy quality expected: 0.67
happy quality: 0.67
expected better: 0.67
terrible product: 0.67
product buy: 0.67


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [4]:
# You code here (Please add comments in the code):

#importing the required libraries
from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Below is the query that I want to search for within the reviews
query = "Great quality and highly recommend"


# 1. Loading pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def get_bert_embedding(text):
    """
    Generate BERT embeddings for a given text.
    """
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=512)
    with torch.no_grad(): #Disabling the calculation of the gradient.
        outputs = model(**inputs)
# Getting the average embedding
    return outputs.last_hidden_state.mean(dim=1)

# 2. Getting BERT embeddings for all reviews and the query
query_embedding = get_bert_embedding(query)
review_embeddings = [get_bert_embedding(review) for review in reviews]

# 3. Cosine similarity between query embedding and each review
similars = [cosine_similarity(query_embedding, review_emb)[0][0] for review_emb in review_embeddings]

# 4. Ranking reviews by similarity in descending order
sorted_idx = np.argsort(similars)[::-1]  # Indices of reviews sorted by similarity

# 5. Displaying ranked results
print("Ranked Reviews by Similarity to Query Designed:")
for idx in sorted_idx:
    print(f"Review: {reviews[idx]}, Similarity: {similars[idx]:.4f}")








/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Ranked Reviews by Similarity to Query Designed:
Review: Fantastic quality! Highly recommend to everyone., Similarity: 0.8353
Review: Not happy with the quality, I expected something better., Similarity: 0.6079
Review: This is a terrible product, I will never buy it again., Similarity: 0.5615
Review: I absolutely love this product! It works amazingly well., Similarity: 0.5597
Review: The product is okay, but not what I had hoped for., Similarity: 0.5452


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Reflective Feedback
Learning Experience:
  This exercise of feature extraction from text data has been quite enlightening, mostly regarding the Natural Language Processing or NLP techniques.
Feature extraction was the most helpful concept because it is a base model for many NLP tasks, including the BoW method and N-grams (bigrams, and trigrams) (AlQahtani, 2021).
I also understood more about POS tagging and the significance of syntactic structures that can be core in analyzing textual data for more probing.
Thus, the course taught me that ranking and selecting features is an essential feature selection technique, as seen in using filter methods when ranking features for importance.

Challenges Encountered:
  In this exercise, the most difficult part was selecting helpful features in text classification.
Raw text data and feature extraction methods such as BoW needed much attention while working with large text data and managing the dimensions.
Another was the use of pre-trained models: For example, for text similarity ranking with BERT, a basic understanding of how BERT embeddings work and how cosine similarity is then measured from these also has its complexities (Lin et al. 2022).
Adjusting for the net features to handle the model's performance was also a strenuous exercise with lots of experimentation.

Relevance to My Field of Study (NLP):
  This exercise is especially closely related to the concepts of NLP. Feature extraction is one of the basic tasks of NLP, irrespective of text classification, sentiment analysis, or information retrieval. For applications in chatbots, document classification, or recommendation systems, the step of feature extraction, selection, and ranking consequently has a critical impact on increasing the accuracy of the result and overall performance of a given system (Abraham et al. 2022).
However, the concentration on BERT for text similarity relates directly with the current climaxes of NLP advancements in that pre-stemming transformer models have transformed approaches to text data.

References
Abraham, E. D., D'Oosterlinck, K., Feder, A., Gat, Y., Geiger, A., Potts, C., ... & Wu, Z. (2022). Cebab: Estimating the causal effects of real-world concepts on nlp model behavior. Advances in Neural Information Processing Systems, 35, 17582-17596.
AlQahtani, A. S. (2021). Product sentiment analysis for Amazon reviews. International Journal of Computer Science & Information Technology (IJCSIT) Vol, 13.
Lin, J., Nogueira, R., & Yates, A. (2022). Pretrained transformers for text ranking: Bert and beyond. Springer Nature.






'''

"\nReflective Feedback\nLearning Experience:\nThis exercise of feature extraction from text data has been quite enlightening, mostly regarding the Natural Language Processing or NLP techniques. \nFeature extraction was the most helpful concept because it is a base model for many NLP tasks, including the BoW method and N-grams (bigrams, and trigrams) (AlQahtani, 2021). \nI also understood more about POS tagging and the significance of syntactic structures that can be core in analyzing textual data for more probing. \nThus, the course taught me that ranking and selecting features is an essential feature selection technique, as seen in using filter methods when ranking features for importance.\n\nChallenges Encountered:\nIn this exercise, the most difficult part was selecting helpful features in text classification. \nRaw text data and feature extraction methods such as BoW needed much attention while working with large text data and managing the dimensions. \nAnother was the use of pre-t